name: 'Firedancer Fuzzbot Builder'
description: 'Provides a build environment for Firedancer on Fuzzbot'
inputs:
  command:
    description: command to execute
    required: true
runs:
  using: 'docker'
  image: 'docker://anthonylh/llvm-patched-libfuzzer'
  args:
    - ${{ inputs.command }}
