name: 'Firedancer Fuzzbot Builder'
description: 'Provides a build environment for Firedancer on Fuzzbot'
inputs:
  command:
    description: command to execute
    required: true
runs:
  steps:
    - name:
      run: |
        ls
        docker --help
